site_name: Beam Documentation
theme: material #readthedocs
theme:
  name: material
  custom_dir: docs/theme
extra_css:
  - docs/theme/css/beam.css
nav:
  - Home: 'index.md'
  - Frequently Asked Questions: 'about/faq.md'
  - Tutorial:
      - 'Part 1': 'tutorials/tutorial1.md'
      - 'Part 2': 'tutorials/tutorial2.md'
      - 'Part 3': 'tutorials/tutorial3.md'
  - User Guide:
      - 'Models': 'user-guide/models.md'
      - 'Databases': 'user-guide/databases.md'
      - 'Backends': 'user-guide/backends.md'
      - 'Expressions': 'user-guide/expressions.md'
      - 'Queries':
        - 'Basic Queries': 'user-guide/queries/basic.md'
        - 'More complex SELECTs': 'user-guide/queries/select.md'
        - 'Ordering': 'user-guide/queries/ordering.md'
        - 'Relationships': 'user-guide/queries/relationships.md'
        - 'Aggregates': 'user-guide/queries/aggregates.md'
        - 'Combining queries': 'user-guide/queries/combining-queries.md'
#        - 'Common data types': 'user-guide/queries/data-types.md'
        - 'Window functions': 'user-guide/queries/window-functions.md'
        - 'Advanced features': 'user-guide/queries/advanced-features.md'
        - 'Common table expressions': 'user-guide/queries/common-table-expressions.md'
      - 'Custom queries': 'user-guide/extensibility.md'
      - 'Data Manipulation':
        - 'INSERT': 'user-guide/manipulation/insert.md'
        - 'UPDATE': 'user-guide/manipulation/update.md'
        - 'DELETE': 'user-guide/manipulation/delete.md'
  - Schema management:
      - 'The Migrations Framework': 'schema-guide/migrations.md'
      - 'The beam-migrate tool': 'schema-guide/tool.md'
      - 'The beam-migrate library': 'schema-guide/library.md'
#      - 'Supported migrations': 'schema-guide/supported.md'
  - Backends:
      - 'beam-postgres': 'user-guide/backends/beam-postgres.md'
      - 'beam-sqlite': 'user-guide/backends/beam-sqlite.md'
      - 'Writing a Custom Backend': 'user-guide/custom-backends.md'
  - About:
      - 'Compatibility Matrix': 'about/compatibility.md'
      - 'License': 'about/license.md'
      - 'Release Notes': 'about/release-notes.md'
markdown_extensions:
  - admonition
  - docs.markdown.beam_query:
      template_dir: 'docs/beam-templates'
      cache_dir: 'docs/.beam-query-cache'
      conf: 'docs/beam.yaml'
      base_dir: '.'
      enabled_backends:
        - beam-postgres
        - beam-sqlite
        # - beam-mysql
        # - beam-mssql
  - docs.markdown.markdown_fenced_code_tabs
  - def_list
  - codehilite
  - footnotes
extra:
  logo: 'img/logo.svg'
repo_name: 'haskell-beam/beam'
repo_url: 'https://github.com/haskell-beam/beam'
