#resolver: lts-9.0
#resolver: lts-10.3
#resolver: lts-10.5
#resolver: lts-12.17
resolver: lts-13.6
#resolver: nightly-2019-09-28
packages:
  - beam-sqlite
  - beam-postgres
  - beam-core
  - beam-migrate
  - beam-migrate-cli

nix:
  shell-file: shell.nix

#extra-deps:
#  - dependent-map-0.2.4.0
#  - dependent-sum-0.5
