#resolver: lts-9.0
#resolver: lts-10.3
#resolver: lts-10.5
resolver: lts-12.17
# resolver: nightly-2018-11-05
packages:
  - beam-sqlite
  - beam-postgres
  - beam-core
  - beam-migrate
  - beam-migrate-cli
nix:
  shell-file: shell.nix
