#!/bin/bash

set -e

rm -r $HOME/venv

if [ ! -d "$HOME/venv/bin" ]; then
    echo "Creating virtual environment"
    virtualenv $HOME/venv
fi

source $HOME/venv/bin/activate

pip install mkdocs==0.17.2 mkdocs-material==2.6.0
pip install --upgrade awscli

echo "Building documentation examples for ${BEAM_DOC_BACKEND}"
sh ./build-docs.sh builddocs
