#!/bin/sh

set -e

if [ ! -d $HOME/venv ]; then
    virtualenv $HOME/venv
fi

$HOME/venv/bin/activate

pip install mkdocs-0.17.2
pip install mkdocs-material-2.6.0

echo "Building documentation examples for ${BEAM_DOC_BACKEND}"
sh ./build-docs.sh builddocs
