#!/bin/bash

set -e

if [ ! -d "$HOME/venv/bin" ]; then
    echo "Creating virtual environment"
    virtualenv $HOME/venv
fi

source $HOME/venv/bin/activate

pip install mkdocs==0.17.2 mkdocs-material==2.6.0
pip install --upgrade awscli
pip install --upgrade sqlparse

fetch_archive() {
    BEAM_DOC_BACKEND=$1
    BEAM_DOC_CACHE_ARCHIVE="${BEAM_DOC_BACKEND}-docs-cache.tar.gz"
    mkdir -p docs/.beam-query-cache
    echo "Fetch ${BEAM_DOC_CACHE_ARCHIVE}"
    aws s3 cp s3://beam-doc-cache/cache/${BEAM_DOC_CACHE_ARCHIVE} ./${BEAM_DOC_CACHE_ARCHIVE}
    tar zxvf ./${BEAM_DOC_CACHE_ARCHIVE}
}

echo "Building docs for ${BEAM_DOC_BACKEND}"

echo "Attempting to download caches"
for backend in $BEAM_DOC_BACKENDS; do
    fetch_archive $backend
done

BEAM_DOC_BACKEND="${BEAM_DOC_BACKENDS}" PYTHONPATH="${PYTHONPATH}:." ./build-docs.sh builddocs
