#!/bin/bash

set -ex

echo "Setting up postgres"

sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-10

sudo /etc/init.d/postgresql stop
/usr/lib/postgresql/10/bin/pg_ctl initdb -D pgdb
/usr/lib/postgresql/10/bin/pg_ctl start -D pgdb

# ubuntu automatically starts the server

echo "Postgres server started"

