#!/bin/bash

set -e

if [ ! -z "$POSTGRES_PATH" ]; then
    export PATH="${POSTGRES_PATH}:${PATH}"
fi
postgres --help
pg_ctl --help

stack --no-terminal build --dump-logs --flag beam-core:werror --flag beam-sqlite:werror --flag beam-postgres:werror --flag beam-migrate:werror --resolver $BEAM_RESOLVER --fast

