#!/bin/bash

#set -e

if [ ! -z "$POSTGRES_PATH" ]; then
    export PATH="${POSTGRES_PATH}:${PATH}"
fi
exec stack --no-terminal test --flag beam-core:werror --flag beam-sqlite:werror --flag beam-postgres:werror --flag beam-migrate:werror --resolver $BEAM_RESOLVER
